name: Build & Release PDFs

on:
  push:
    tags:
      - '*'   # any tag -> release

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache TeX Live packages
        uses: actions/cache@v4
        with:
          path: |
            /usr/share/texlive
            /usr/share/texmf
            /var/lib/texmf
            /usr/bin/tex*
            /usr/bin/lua*
            /usr/bin/biber
            /usr/bin/latexmk
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/*.tex', 'preamble.tex') }}
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Install TeX Live + deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-binaries \
            texlive-luatex \
            texlive-bibtex-extra \
            biber \
            latexmk \
            make

      - name: Build all PDFs (LuaLaTeX via latexmk)
        run: |
          make release-build
          ls -l *.pdf || echo "No PDFs found in root."

      - name: Create / Update GitHub Release and upload PDFs
        uses: softprops/action-gh-release@v2
        with:
          files: "*.pdf"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
